-- Create historico_movimentacoes table
create table if not exists public.historico_movimentacoes (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  alteracao text null,
  user_id uuid null,
  pedido_id uuid null,
  constraint historico_movimentacoes_pkey primary key (id),
  constraint historico_movimentacoes_pedido_id_fkey foreign key (pedido_id) references pedidos (id) on delete cascade,
  constraint historico_movimentacoes_user_id_fkey foreign key (user_id) references usuarios (id) on delete set null
) tablespace pg_default;

-- Create index for better query performance
create index if not exists historico_movimentacoes_pedido_id_idx on public.historico_movimentacoes(pedido_id);
create index if not exists historico_movimentacoes_user_id_idx on public.historico_movimentacoes(user_id);
create index if not exists historico_movimentacoes_created_at_idx on public.historico_movimentacoes(created_at desc);

-- Enable RLS
alter table public.historico_movimentacoes enable row level security;

-- Create policy for reading historico_movimentacoes
create policy "Enable read access for authenticated users" on public.historico_movimentacoes
  for select
  using (auth.role() = 'authenticated');

-- Create policy for inserting historico_movimentacoes
create policy "Enable insert access for authenticated users" on public.historico_movimentacoes
  for insert
  with check (auth.role() = 'authenticated');
