-- Create status_upsell table if not exists
create table if not exists public.status_upsell (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  status text null,
  constraint status_upsell_pkey primary key (id)
);

-- Enable RLS
alter table public.status_upsell enable row level security;

-- Create policy to allow all operations for authenticated users
create policy "Allow all operations for authenticated users"
  on public.status_upsell
  for all
  to authenticated
  using (true)
  with check (true);

-- Insert default status if table is empty
insert into public.status_upsell (status)
select * from (
  values 
    ('Aguardando aumento'),
    ('Aumentado'),
    ('Não aumentado'),
    ('Aumento grátis')
) as default_status(status)
where not exists (select 1 from public.status_upsell);
