-- Tabela de formas de pagamento
create table if not exists public.formas_pagamentos (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  nome text null,
  img_url text null,
  constraint formas_pagamentos_pkey primary key (id)
) tablespace pg_default;

-- Enable RLS
alter table public.formas_pagamentos enable row level security;

-- Create policies
create policy "Allow read access to all users"
  on public.formas_pagamentos
  for select
  using (true);

create policy "Allow insert for authenticated users"
  on public.formas_pagamentos
  for insert
  with check (auth.role() = 'authenticated');

create policy "Allow update for authenticated users"
  on public.formas_pagamentos
  for update
  using (auth.role() = 'authenticated');

create policy "Allow delete for authenticated users"
  on public.formas_pagamentos
  for delete
  using (auth.role() = 'authenticated');
