// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rllypkctvckeaczjesht.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJsbHlwa2N0dmNrZWFjemplc2h0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MzYwOTgsImV4cCI6MjA3NDQxMjA5OH0.Gc4WWo0YBE3eiB85lYh_1IjheXdFzPD7KwgcLiVV70s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});